In [1]:
# import libraries

import os
import numpy as np
import pandas as pd
import urllib.parse
from urllib.parse import unquote

In [2]:
import pickle
with open('Mistral_Games.pickle', 'rb') as file:
    Mistral_Games = pickle.load(file)

In [3]:
df = pd.DataFrame.from_dict(Mistral_Games, orient='index')
df.head()

,rep0,rep1,rep2,rep3,rep4,rep5,rep6,rep7,rep8,rep9,...,rep35,rep36,rep37,rep38,rep39,rep40,rep41,rep42,rep43,rep44
Asteroid->Viking,"[Comet_Shoemaker-Levy_9, Magnesium, Scotland, ...","[Venus, Nitrogen, Oxygen, Sweden, Viking]","[Comet_Shoemaker-Levy_9, Moon, Mars, European_...","[Venus, European_Space_Agency, Norway, Viking]","[Venus, Nitrogen, Natural_gas, September_11,_2...","[Venus, Nitrogen, Natural_gas, Ocean, Norse_my...","[Venus, Nitrogen, Nitrogen_fixation, Earth's_a...","[Carl_Friedrich_Gauss, Denmark, Viking]","[1_Ceres, Mars, Nitrogen, Natural_gas, Ocean, ...","[Dinosaur, Scotland, Norway, Viking]",...,"[Earth, Norse_mythology, Norway, Viking]","[Mars, Nitrogen, Food, Vitamin_D, Vitamin, Sco...","[Venus, Vietnam, Vietnam, 13th_century, Norway...","[Comet_Shoemaker-Levy_9, Moon, Ireland, Viking]","[Solar_System, Nickel, List_of_elements_by_nam...","[Venus, Vietnam, Vietnam, 11th_century, Viking]","[Venus, Nitrogen, Carbon_dioxide, Scotland, No...","[Trojan_War, Virgil, Odyssey, Egypt, Scramble_...","[Comet_Shoemaker-Levy_9, Solar_System, Extraso...","[1_Ceres, Eris_(dwarf_planet), Asteroid, Venus..."
Brain->Telephone,"[Computer_science, Computer_programming, Micro...","[Computer_science, Computer_programming, Micro...","[Computer_science, Information, Communication,...","[Computer_science, Information, Communication,...","[Computer_science, Information, Communication,...","[Computer_science, Information, Communication,...","[Computer_science, Information, Communication,...","[Computer_science, Information, Communication,...","[Computer_science, Computer_programming, Progr...","[Computer_science, Computer_programming, Progr...",...,"[Computer_science, Computer_programming, Progr...","[Computer_science, Information, Communication,...","[Computer_science, Information, Mass_media, Te...","[Computer_science, Computer_programming, Progr...","[Computer_science, Computer_programming, Micro...","[Computer_science, Programming_language, Compu...","[Computer_science, Information, Communication,...","[Eye, Protein, Computer_science, Information, ...","[Eye, Human, Communication, Telephone]","[Computer_science, Information, Communication,..."
Theatre->Zebra,"[India, Mammal, Zebra]","[Dance, Animal, Mammal, Zebra]","[Brazil, Africa, Horn_of_Africa, Mammal, Zebra]","[United_Kingdom, Anne_of_Great_Britain, North_...","[India, Wheat, Maize, Africa, Anthropology, Hu...","[India, Mammal, Zebra]","[Brazil, Africa, African_Great_Lakes, Africa, ...","[India, Mammal, Zebra]","[India, Mammal, Zebra]","[India, Mammal, Zebra]",...,"[India, Mammal, Zebra]","[United_Kingdom, Anne_of_Great_Britain, North_...","[France, AIDS, Africa, Zulu, South_Africa, Afr...","[United_Kingdom, Arctic_Monkeys, Australia, Ma...","[Switzerland, Zürich, Austria, Ancient_Rome, A...","[United_Kingdom, United_States_dollar, Gold_st...","[India, Mammal, Zebra]","[Switzerland, Austria, Ancient_Rome, Age_of_En...","[Dance, Animal, Mammal, Zebra]","[United_Kingdom, Anne_of_Great_Britain, Mary_I..."
Pyramid->Bean,"[Mexico_City, Philippines, Mango, Fruit, Bean]","[Volleyball, Italy, Agriculture, Vegetable, Bean]","[California, Fruit, Bean]","[California, Fruit, Bean]","[California, Vegetable, Bean]","[Mexico_City, London, Culture, Agriculture, Fo...","[Earth, Plant, Agriculture, Food, Cereal, Seed...","[Basketball, United_States_Virgin_Islands, Hur...","[Mexico_City, United_States_dollar, Banknote, ...","[Mexico, Agriculture, Food, Cereal, Fruit, Bean]",...,"[Egyptian_pyramids, Ancient_Egypt, Agriculture...","[California, Vegetable, Bean]","[California, Vegetable, Bean]","[Mexico_City, United_States_dollar, Banknote, ...","[France, French_language, Canada, English_lang...","[California, Vegetable, Bean]","[California, Vegetable, Bean]","[California, Vegetable, Bean]","[Mexico_City, Latin_America, United_States_Vir...","[Egyptian_pyramids, Ancient_Egypt, Virgil, Ast..."
Batman->Wood,"[Earthquake, Earth, Plant, Wood]","[Spring_Heeled_Jack, Nature, Earth's_atmospher...","[Earthquake, Natural_gas, Pollution, Fossil_fu...","[Scotland, French_language, United_States, Wes...","[Earthquake, Earth, Food, Cereal, Africa, East...","[Earthquake, Tsar_Bomba, Arctic_Circle, Temper...","[Earthquake, Tsar_Bomba, Arctic_Circle, Temper...","[Scotland, Country, Wales, Welsh_law, Wales, P...","[Scotland, Wales, Tony_Blair, Wales, Folk_musi...","[Earthquake, California, Wine, Eastern_Orthodo...",...,"[Earthquake, Earth, Tropical_cyclone, Oceania,...","[Chemistry, Biology, Botany, Wood]","[Scotland, World_War_II, United_States_Congres...","[Earthquake, Tsar_Bomba, Arctic_Circle, United...","[Scotland, Wales, Welsh_law, Archbishop_of_Can...","[Scotland, World_War_II, United_Kingdom, Frenc...","[Scotland, Wales, Welsh_law, 17th_century, Bri...","[Chemistry, Organism, Food, Biodiversity, Trop...","[Scotland, World_War_II, United_Nations, Winst...","[Chemistry, Crystal, Quartz, Metamorphic_rock,..."

In [4]:
list_of_lists = []
for key in Mistral_Games:
    for i in range(len(Mistral_Games[key])):
        list_of_lists.append([key, Mistral_Games[key][f'rep{i}'], i])

df = pd.DataFrame(list_of_lists, columns=['game', 'results', 'rep'])
df

,game,results,rep
0,Asteroid->Viking,"[Comet_Shoemaker-Levy_9, Magnesium, Scotland, ...",0
1,Asteroid->Viking,"[Venus, Nitrogen, Oxygen, Sweden, Viking]",1
2,Asteroid->Viking,"[Comet_Shoemaker-Levy_9, Moon, Mars, European_...",2
3,Asteroid->Viking,"[Venus, European_Space_Agency, Norway, Viking]",3
4,Asteroid->Viking,"[Venus, Nitrogen, Natural_gas, September_11,_2...",4
...,...,...,...
1889,China->Birth_control,"[Human, Humanism, Human_rights, Humanism, Educ...",25
1890,China->Birth_control,"[Human, Humanism, Human_rights, Biology, Medic...",26
1891,China->Birth_control,"[Human, Humanism, Education, Medicine, Biology...",27
1892,China->Birth_control,"[Human, Buddhism, Psychology, Biology, Medicin...",28
1893,China->Birth_control,"[Republic_of_China, Buddhism, Religion, People...",29